use js_export_macro::js_export;
use miden_client::note::Note as NativeNote;
use miden_client::transaction::TransactionRequest as NativeTransactionRequest;
use miden_client::vm::AdviceMap as NativeAdviceMap;
use miden_client::Word as NativeWord;

use crate::models::advice_map::AdviceMap;
use crate::models::note::Note;
use crate::models::word::Word;
use crate::platform::{JsBytes, JsErr};
use crate::utils::{deserialize_from_bytes, serialize_to_bytes};

pub mod note_and_args;
pub mod note_details_and_tag;
pub mod note_id_and_args;
pub mod transaction_request_builder;

use note_details_and_tag::NoteDetailsAndTag;

/// Specifies a transaction request that can be executed by an account.
///
/// A request contains information about input notes to be consumed by the transaction (if any),
/// description of the transaction script to be executed (if any), and a set of notes expected to be
/// generated by the transaction or by consuming notes generated by the transaction.
#[derive(Clone)]
#[js_export]
pub struct TransactionRequest(NativeTransactionRequest);

#[js_export]
impl TransactionRequest {
    /// Serializes the transaction request into bytes.
    pub fn serialize(&self) -> JsBytes {
        serialize_to_bytes(&self.0)
    }

    /// Deserializes a transaction request from bytes.
    pub fn deserialize(bytes: JsBytes) -> Result<TransactionRequest, JsErr> {
        deserialize_from_bytes::<NativeTransactionRequest>(&bytes).map(TransactionRequest)
    }

    /// Returns output notes created by the sender account.
    #[js_export(js_name = "expectedOutputOwnNotes")]
    pub fn expected_output_own_notes(&self) -> Result<Vec<Note>, JsErr> {
        let native_notes: Vec<NativeNote> = self.0.expected_output_own_notes();
        let notes: Vec<Note> = native_notes.into_iter().map(Into::into).collect();
        Ok(notes)
    }

    /// Returns notes expected to be created in subsequent executions.
    #[js_export(js_name = "expectedFutureNotes")]
    pub fn expected_future_notes(&self) -> Result<Vec<NoteDetailsAndTag>, JsErr> {
        self.0
            .expected_future_notes()
            .cloned()  // This converts &(T, U) to (T, U)
            .map(|(note_details, note_tag)| {
                Ok(NoteDetailsAndTag::new(
                    note_details.into(),
                    note_tag.into()
                ))
            })
            .collect::<Result<Vec<NoteDetailsAndTag>, _>>()
    }

    /// Returns the transaction script argument if present.
    #[js_export(js_name = "scriptArg")]
    pub fn script_arg(&self) -> Option<Word> {
        self.0.script_arg().map(Word::from)
    }

    /// Returns the authentication argument if present.
    #[js_export(js_name = "authArg")]
    pub fn auth_arg(&self) -> Option<Word> {
        self.0.auth_arg().map(Word::from)
    }

    /// Returns a copy of the advice map carried by this request.
    #[js_export(js_name = "adviceMap")]
    pub fn advice_map(&self) -> AdviceMap {
        self.0.advice_map().into()
    }

    /// Returns a copy of this request carrying `auth_arg` as its auth argument.
    ///
    /// Since protocol 0.16 `fee::pay_fee` reads the fee faucet and conversion rate from the auth
    /// args, so a request that pays a fee must carry the commitment
    /// `hash(CONVERSION_INFO || SALT)` — and a request that has already been SERIALIZED cannot
    /// otherwise acquire one, because `TransactionRequest` is only constructible through its
    /// builder. That blocks every flow whose bytes are produced elsewhere and handed over:
    /// bridged sends, earn deposits, swaps, and a dApp's own `execute` request, none of which the
    /// wallet can rebuild.
    ///
    /// Deliberately NOT `withFeeConversionInfo`: that flags the request as declaring conversion
    /// info, which makes the client classify the account's auth component first and reject an
    /// account whose component it cannot match. This attaches the word and nothing else.
    ///
    /// Overwrites any existing auth arg. The commitment's preimage still has to be reachable, so
    /// pair this with `extendAdviceMap`.
    #[js_export(js_name = "withAuthArg")]
    pub fn with_auth_arg(&self, auth_arg: &Word) -> TransactionRequest {
        let native_auth_arg: NativeWord = auth_arg.into();
        self.0.clone().with_auth_arg(native_auth_arg).into()
    }

    /// Returns a copy of this request with `advice_map` merged into its advice map.
    ///
    /// Entries are merged with last-write-wins semantics: a key already present in the request is
    /// overwritten by the value from `advice_map`. Use this to inject advice (e.g. a signature
    /// produced by an external signer) after the request has already been built.
    #[js_export(js_name = "extendAdviceMap")]
    pub fn extend_advice_map(&self, advice_map: &AdviceMap) -> TransactionRequest {
        let native_advice_map: NativeAdviceMap = advice_map.into();
        let mut native_request = self.0.clone();
        native_request
            .advice_map_mut()
            .extend(native_advice_map.iter().map(|(key, value)| (*key, value.clone())));
        native_request.into()
    }
}

// CONVERSIONS
// ================================================================================================

impl From<TransactionRequest> for NativeTransactionRequest {
    fn from(transaction_request: TransactionRequest) -> Self {
        transaction_request.0
    }
}

impl From<&TransactionRequest> for NativeTransactionRequest {
    fn from(transaction_request: &TransactionRequest) -> Self {
        transaction_request.0.clone()
    }
}

impl From<NativeTransactionRequest> for TransactionRequest {
    fn from(transaction_request: NativeTransactionRequest) -> Self {
        TransactionRequest(transaction_request)
    }
}

impl From<&NativeTransactionRequest> for TransactionRequest {
    fn from(transaction_request: &NativeTransactionRequest) -> Self {
        TransactionRequest(transaction_request.clone())
    }
}
