use js_export_macro::js_export;
use miden_client::note::Note as NativeNote;
use miden_client::transaction::TransactionRequest as NativeTransactionRequest;
use miden_client::vm::AdviceMap as NativeAdviceMap;

use crate::models::advice_map::AdviceMap;
use crate::models::note::Note;
use crate::models::word::Word;
use crate::platform::{JsBytes, JsErr};
use crate::utils::{deserialize_from_bytes, serialize_to_bytes};

pub mod note_and_args;
pub mod note_details_and_tag;
pub mod note_id_and_args;
pub mod transaction_request_builder;

use note_details_and_tag::NoteDetailsAndTag;

/// Specifies a transaction request that can be executed by an account.
///
/// A request contains information about input notes to be consumed by the transaction (if any),
/// description of the transaction script to be executed (if any), and a set of notes expected to be
/// generated by the transaction or by consuming notes generated by the transaction.
#[derive(Clone)]
#[js_export]
pub struct TransactionRequest(NativeTransactionRequest);

#[js_export]
impl TransactionRequest {
    /// Serializes the transaction request into bytes.
    pub fn serialize(&self) -> JsBytes {
        serialize_to_bytes(&self.0)
    }

    /// Deserializes a transaction request from bytes.
    pub fn deserialize(bytes: JsBytes) -> Result<TransactionRequest, JsErr> {
        deserialize_from_bytes::<NativeTransactionRequest>(&bytes).map(TransactionRequest)
    }

    /// Returns output notes created by the sender account.
    #[js_export(js_name = "expectedOutputOwnNotes")]
    pub fn expected_output_own_notes(&self) -> Result<Vec<Note>, JsErr> {
        let native_notes: Vec<NativeNote> = self.0.expected_output_own_notes();
        let notes: Vec<Note> = native_notes.into_iter().map(Into::into).collect();
        Ok(notes)
    }

    /// Returns notes expected to be created in subsequent executions.
    #[js_export(js_name = "expectedFutureNotes")]
    pub fn expected_future_notes(&self) -> Result<Vec<NoteDetailsAndTag>, JsErr> {
        self.0
            .expected_future_notes()
            .cloned()  // This converts &(T, U) to (T, U)
            .map(|(note_details, note_tag)| {
                Ok(NoteDetailsAndTag::new(
                    note_details.into(),
                    note_tag.into()
                ))
            })
            .collect::<Result<Vec<NoteDetailsAndTag>, _>>()
    }

    /// Returns the transaction script argument if present.
    #[js_export(js_name = "scriptArg")]
    pub fn script_arg(&self) -> Option<Word> {
        self.0.script_arg().map(Word::from)
    }

    /// Returns the authentication argument if present.
    ///
    /// A request built by a builder that called neither `withAuthArg` nor `withFeeConversionSalt`
    /// has none: the client commits fee conversion info into the auth args while preparing the
    /// transaction, which is after this can observe it.
    ///
    /// There is deliberately no setter here. An auth argument can only be set through
    /// `TransactionRequestBuilder.withAuthArg`, because miden-client keeps it mutually exclusive
    /// with the fee conversion salt and enforces that on the builder — a setter on a finished
    /// request would sit outside that exclusion.
    #[js_export(js_name = "authArg")]
    pub fn auth_arg(&self) -> Option<Word> {
        self.0.auth_arg().map(Word::from)
    }

    /// Returns the fee conversion salt this request declares, if any.
    ///
    /// Declared through `TransactionRequestBuilder.withFeeConversionSalt`, and carried through
    /// serialization, so a request transported to a co-signer still names the salt its summary
    /// was derived under. `undefined` means none was declared: miden-client then commits the
    /// chain's native conversion info under its own fixed default salt, which is what every
    /// account other than a multisig wants.
    ///
    /// Mutually exclusive with `authArg` — setting either clears the other on the builder.
    #[js_export(js_name = "feeConversionSalt")]
    pub fn fee_conversion_salt(&self) -> Option<Word> {
        self.0.fee_conversion_salt().map(Word::from)
    }

    /// Returns a copy of the advice map carried by this request.
    #[js_export(js_name = "adviceMap")]
    pub fn advice_map(&self) -> AdviceMap {
        self.0.advice_map().into()
    }

    /// Returns a copy of this request with `advice_map` merged into its advice map.
    ///
    /// Entries are merged with last-write-wins semantics: a key already present in the request is
    /// overwritten by the value from `advice_map`. Use this to inject advice (e.g. a signature
    /// produced by an external signer) after the request has already been built.
    #[js_export(js_name = "extendAdviceMap")]
    pub fn extend_advice_map(&self, advice_map: &AdviceMap) -> TransactionRequest {
        let native_advice_map: NativeAdviceMap = advice_map.into();
        let mut native_request = self.0.clone();
        native_request
            .advice_map_mut()
            .extend(native_advice_map.iter().map(|(key, value)| (*key, value.clone())));
        native_request.into()
    }
}

// CONVERSIONS
// ================================================================================================

impl From<TransactionRequest> for NativeTransactionRequest {
    fn from(transaction_request: TransactionRequest) -> Self {
        transaction_request.0
    }
}

impl From<&TransactionRequest> for NativeTransactionRequest {
    fn from(transaction_request: &TransactionRequest) -> Self {
        transaction_request.0.clone()
    }
}

impl From<NativeTransactionRequest> for TransactionRequest {
    fn from(transaction_request: NativeTransactionRequest) -> Self {
        TransactionRequest(transaction_request)
    }
}

impl From<&NativeTransactionRequest> for TransactionRequest {
    fn from(transaction_request: &NativeTransactionRequest) -> Self {
        TransactionRequest(transaction_request.clone())
    }
}
