name: Build
on:
  push:
    branches: [main, next]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  build-wasm:
    name: Build Client for Wasm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        run: rustup update --no-self-update
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: make - build-wasm
        run: make build-wasm
