name: Lint
permissions:
  contents: read
on:
  push:
    branches: [main, next]
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  typos:
    name: Spellcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: typos@1.42.0
      - run: make typos-check

  toml:
    name: Toml formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.10.0
      - run: make toml-check

  eslint:
    name: Typescript eslint checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: make rust-client-ts-lint

  clippy-wasm:
    name: Clippy WASM
    runs-on: ubuntu-24.04
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with nightly clippy
        run: |
          rustup update --no-self-update nightly
          rustup target add --toolchain nightly wasm32-unknown-unknown
          rustup +nightly component add clippy
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.6
      - name: make - clippy-wasm
        run: make clippy-wasm
      - name: Show sccache stats
        if: always()
        run: sccache --show-stats || true

  format:
    name: Format check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - name: Install prettier
        run: yarn install
      - name: make - format-check
        run: make format-check

